spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true