spring:
  datasource:
    url: jdbc:p6spy:h2:tcp://localhost/~/Users/kakao/2023/kakao/onboarding/h2/db:querydsl
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    #    show_sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

logging:
  level:
    p6spy: info